config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  get 'forum_thread/:id/follows', to: 'forum_threads#follows', as: :follows
  get 'forum_thread/:id/unfollows', to: 'forum_threads#unfollows', as: :unfollows
  get 'user/:id/mis_foros', to: 'users#mis_foros', as: :mis_foros
  get 'forum_thread/:id/forum_posts?forum_thread=:id/likes', to: 'forum_posts#likes', as: :likes
  get 'user/:id/mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
  get 'estadisticas', to: 'estadisticas#show', as: :estadisticas
  #match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users do
    get 'mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
    get 'destroy', to: 'users#destroy', as: :destroy
  end

  resources :forum_threads do
    resources :requests do

      get 'aceptar', to: 'requests#aceptar', as: :aceptar
      get 'rechazar', to: 'requests#rechazar', as: :rechazar
    end

    resources :polls do
      resources :answers do
        put 'vote', to: 'answers#vote', as: :vote
      end
    end

  	resources :forum_posts do

      get 'likes', to: 'forum_posts#likes', as: :likes
      get 'favoritos', to: 'forum_posts#favoritos', as: :favoritos
      get 'sacar_favoritos', to: 'forum_posts#sacar_favoritos', as: :sacar_favoritos
      get 'dislikes', to: 'forum_posts#dislikes', as: :dislikes

      resources :comments do
        get 'likes', to: 'comments#likes', as: :likes
        get 'dislikes', to: 'comments#dislikes', as: :dislikes
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, authentication_keys: [:login]

  devise :omniauthable, omniauth_providers: [:facebook]

  validates :username, presence: true, uniqueness: { case_sensitive: true }
  validates :username, format: { with: /^[a-zA-Z0-9_\.]*$/, multiline: true }

  has_many :forum_threads, dependent: :destroy
  has_many :forum_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :polls, dependent: :destroy

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100#' },
                             default_url: ':style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  acts_as_liker
  acts_as_follower
  acts_as_voter

  attr_writer :login

  def login
    @login || username || email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where([
                                'lower(username) =
                                 :value OR lower(email) = :value', {
                                   value: login.downcase
                                 }
                              ]).first

    elsif conditions[:username].nil?
      where(conditions).first
    else
      where(username: conditions[:username]).first
    end
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
        u.email = auth.info.email
        u.password = Devise.friendly_token(length = 10)
        u.username = auth.info.email.split(/#|@/).first
        u.last_name = auth.info.last_name
        u.first_name = auth.info.first_name
        u.save!
        logger.info '>> ENVIANDO USER <<'
        return u
        logger.info '>> USER ENVIADO <<'
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    logger.info '>>>> FACEBOOK LOG IN INITIATED <<<<'

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook')
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    logger.info '>>>> FACEBOOK LOG IN FAILED <<<<'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def mis_foros
    @user = User.find(params[:id])
  end

  def mis_publicaciones
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id]).destroy
    redirect_to user_path(current_user), notice: 'User deleted.'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def normalimage
    "http://graph.facebook.com/#{uid}/picture?type=normal"
  end
end

app/views/users/mis_foros.html.erb
<h3>Mis Foros</h3>


<% if @user.followees(ForumThread).any? %>
  <ul>
    <% @user.followees(ForumThread).each do |forum_thread| %>
      <div class="row">
        <p>
          <%= link_to forum_thread.subject, forum_thread %>
          <% if can? :destroy, forum_thread %>
            <td><%= link_to 'Eliminar', forum_thread, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
          <% end %>

          <small>
            Creado por <strong><%= forum_thread.user.username %></strong>. <%= forum_thread.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>
          </small>
          &emsp;<strong>Publicaciones: <%= forum_thread.forum_posts.count %></strong> 

          <div>
            <% if user_signed_in? %>
              <% if current_user.follows?(forum_thread) %>
                  <%= link_to 'Dejar de seguir', unfollows_path(forum_thread) %>
              <% end %>
            <%end%>
          </div>
        </p>
      </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>
    No sigues ningun foro.
  </p>
<% end %>

app/views/users/mis_publicaciones.html.erb
<h1>Mis publicaciones favoritas</h1>


<% if @user.followees(ForumPost).any? %>
  <ul>
    <% @user.followees(ForumPost).each do |forum_post| %>
      <div class="row">
        <p>
          <strong><%= link_to forum_post.title, forum_thread_forum_post_path(forum_post.forum_thread, forum_post) %></strong>
        </p>

        <small>
            Creado por <strong><%= forum_post.forum_thread.user.username %></strong>. <%= forum_post.forum_thread.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>
        </small>

      <div>
        <% if user_signed_in? %>
          <% if current_user.follows?(forum_post) %>
              <small><%= link_to 'Sacar de mis favoritas', forum_thread_forum_post_sacar_favoritos_path(forum_post.forum_thread, forum_post) %></small>
            <% end %>
          <%end%>
      </div>

    <% end %>
  </ul>

<% else %>
  <p>
    No tienes publicaciones favoritas.
  </p>
<% end %>  

app/views/users/show.html.erb
<h3>Perfil</h3>


<p class="round-image-100"><%= image_tag(current_user.avatar.url(:thumb)) %></p>
<p>Usuario: <strong><%= @user.username %></strong></p>
<p>Correo: <strong><%= @user.email %></strong></p>
<p>Nombre: <strong><%= @user.first_name %> <%= @user.last_name %></strong></p>




<% rep = 0 %>
<% ForumPost.where(user_id: @user.id).each do |post| %>
	<% rep += post.get_likes.size %>
	<% rep -= post.get_dislikes.size %>

<% end %>


<p>Reputación: <strong><%= rep %></strong></p>
	
<br>

<% if current_user.id == @user.id %>
	<%= link_to "Editar Perfil", edit_user_registration_url %>
<% end %>

<% if @user.admin %>
	<p>Eres admin</p>
	<h3>Usuarios Registrados</h3>
	<% User.all.each do |user| %>
		<% if user.id != @user.id %>
			<p> <%=user.username%> </p>
			<%= link_to "Destroy", user_destroy_path(user), data: { confirm: "You sure?" } %>
		<%end%>
	<% end %>

	<h4>Solicitudes moderador</h4>
	<ul>
	<% Request.where(state: "Pendiente").each do |request| %>
		<% user = User.find(request.user_id) %>
		<% forum = ForumThread.find(request.forum_thread_id) %>
		<li><strong><%= user.username %></strong> ha postulado al foro <strong><%= forum.subject %></strong> | <%= link_to 'Aceptar', forum_thread_request_aceptar_path(forum.id, request.id) %> | <%= link_to 'Rechazar', forum_thread_request_rechazar_path(forum.id, request.id) %>
	<% end %>	
	</ul>
	<%= link_to "Estadísticas", estadisticas_path %>


<% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>