config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  get 'forum_thread/:id/follows', to: 'forum_threads#follows', as: :follows
  get 'forum_thread/:id/unfollows', to: 'forum_threads#unfollows', as: :unfollows
  get 'user/:id/mis_foros', to: 'users#mis_foros', as: :mis_foros
  get 'forum_thread/:id/forum_posts?forum_thread=:id/likes', to: 'forum_posts#likes', as: :likes
  get 'user/:id/mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
  get 'estadisticas', to: 'estadisticas#show', as: :estadisticas
  #match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users do
    get 'mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
    get 'destroy', to: 'users#destroy', as: :destroy
  end

  resources :forum_threads do
    resources :requests do

      get 'aceptar', to: 'requests#aceptar', as: :aceptar
      get 'rechazar', to: 'requests#rechazar', as: :rechazar
    end

    resources :polls do
      resources :answers do
        put 'vote', to: 'answers#vote', as: :vote
      end
    end

  	resources :forum_posts do

      get 'likes', to: 'forum_posts#likes', as: :likes
      get 'favoritos', to: 'forum_posts#favoritos', as: :favoritos
      get 'sacar_favoritos', to: 'forum_posts#sacar_favoritos', as: :sacar_favoritos
      get 'dislikes', to: 'forum_posts#dislikes', as: :dislikes

      resources :comments do
        get 'likes', to: 'comments#likes', as: :likes
        get 'dislikes', to: 'comments#dislikes', as: :dislikes
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  before_action :set_request, only: %i[show edit update destroy]
  before_action :set_forum_thread

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show; end

  def aceptar
    @request = Request.find(params[:request_id])
    @request.state = 'Aceptado'
    @request.save

    redirect_to user_path(current_user)
  end

  def rechazar
    @request = Request.find(params[:request_id])
    @request.state = 'Rechazado'
    @request.save

    redirect_to user_path(current_user)
  end

  # GET /requests/new
  def new
    @request = @forum_thread.requests.build
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = @forum_thread.requests.build(user_id: current_user.id,
                                            forum_thread_id: :forum_thread_id)

    respond_to do |format|
      if @request.save
        format.html do
          redirect_to @forum_thread,
                      notice: 'Request was successfully created.'
        end
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json do
          render json: @request.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html do
          redirect_to @request,
                      notice: 'Request was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json do
          render json: @request.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html do
        redirect_to requests_url,
                    notice: 'Request was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:user_id, :forum_thread_id)
  end

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:forum_thread_id])
  end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for([@forum_thread, request]) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :request_user_id %>
  </div>

  <div class="field">
    <%= form.label :forum_thread_id %>
    <%= form.number_field :forum_thread_id, id: :request_forum_thread_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Forum thread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.user_id %></td>
        <td><%= request.forum_thread_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', forum_threads_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<p>
  <strong>Forum thread:</strong>
  <%= @request.forum_thread_id %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>