config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  get 'forum_thread/:id/follows', to: 'forum_threads#follows', as: :follows
  get 'forum_thread/:id/unfollows', to: 'forum_threads#unfollows', as: :unfollows
  get 'user/:id/mis_foros', to: 'users#mis_foros', as: :mis_foros
  get 'forum_thread/:id/forum_posts?forum_thread=:id/likes', to: 'forum_posts#likes', as: :likes
  get 'user/:id/mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
  get 'estadisticas', to: 'estadisticas#show', as: :estadisticas
  #match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users do
    get 'mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
    get 'destroy', to: 'users#destroy', as: :destroy
  end

  resources :forum_threads do
    resources :requests do

      get 'aceptar', to: 'requests#aceptar', as: :aceptar
      get 'rechazar', to: 'requests#rechazar', as: :rechazar
    end

    resources :polls do
      resources :answers do
        put 'vote', to: 'answers#vote', as: :vote
      end
    end

  	resources :forum_posts do

      get 'likes', to: 'forum_posts#likes', as: :likes
      get 'favoritos', to: 'forum_posts#favoritos', as: :favoritos
      get 'sacar_favoritos', to: 'forum_posts#sacar_favoritos', as: :sacar_favoritos
      get 'dislikes', to: 'forum_posts#dislikes', as: :dislikes

      resources :comments do
        get 'likes', to: 'comments#likes', as: :likes
        get 'dislikes', to: 'comments#dislikes', as: :dislikes
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum_post.rb
# frozen_string_literal: true

class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread
  has_many   :comments, dependent: :destroy

  validates :body, presence: true
  validates :title, presence: true

  acts_as_likeable
  acts_as_followable
  acts_as_votable
end

app/controllers/forum_posts_controller.rb
# frozen_string_literal: true

class ForumPostsController < ApplicationController
  before_action :set_forum_thread

  def index
    @q = @forum_thread.forum_posts.search(params[:q])
    @forum_posts = @q.result
  end

  def new
    @forum_post = @forum_thread.forum_posts.build
  end

  def favoritos
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_post = @forum_thread.forum_posts.find(params[:forum_post_id])
    @user.follow!(@forum_post)
    redirect_to forum_thread_forum_posts_url
  end

  def sacar_favoritos
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_post = @forum_thread.forum_posts.find(params[:forum_post_id])
    @user.unfollow!(@forum_post)
    redirect_to mis_publicaciones_path(@user)
  end

  def dislikes
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_post = @forum_thread.forum_posts.find(params[:forum_post_id])
    @forum_post.disliked_by @user
    redirect_to forum_thread_forum_posts_url
  end

  def likes
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_post = @forum_thread.forum_posts.find(params[:forum_post_id])
    @forum_post.liked_by @user
    redirect_to forum_thread_forum_posts_url
  end

  def edit
    @forum_post = @forum_thread.forum_posts.find(params[:id])
  end

  def show
    @forum_post = @forum_thread.forum_posts.find(params[:id])
  end

  def update
    @forum_post = @forum_thread.forum_posts.find(params[:id])
    respond_to do |format|
      if @forum_post.update(forum_post_params)
        format.html do
          redirect_to forum_thread_forum_posts_url,
                      notice: 'Publicación correctamente actualizada.'
        end
        format.json { render :show, status: :ok, location: @forum_post }
      else
        format.html { render :edit }
        format.json do
          render json: @forum_post.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def create
    @forum_post = @forum_thread.forum_posts.build(
      forum_post_params
    )
    @forum_post.user         = current_user
    @forum_post.forum_thread = @forum_thread
    @forum_post.save

    redirect_to forum_thread_forum_posts_url
  end

  def destroy
    @forum_post = @forum_thread.forum_posts.find(params[:id]).destroy

    redirect_to forum_thread_forum_posts_url
  end

  private

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:forum_thread_id])
  end

  def forum_post_params
    params.require(:forum_post).permit(:forum_thread_id, :user_id, :title,
                                       :body, :forum_post_id)
  end
end

app/helpers/forum_posts_helper.rb
# frozen_string_literal: true

module ForumPostsHelper
  def ya_postulo(user_id, forum_thread_id)
    Request.all.each do |request|
      if (request.user_id == user_id) &&
         (request.forum_thread_id == forum_thread_id)
        return true
      else
        return false
      end
    end
    false
  end
end

app/views/forum_posts/_form.html.erb
<%= form_for([@forum_thread, forum_post]) do |form| %>
  <% if forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% forum_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_area :title, id: :forum_post_title %>
  </div>

  <div class="field">
    <%= form.label :Contenido %>
    <%= form.cktext_area :body, id: :forum_post_body, ckeditor: { language: 'es'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editar Publicación</h1>

<%= render 'form', forum_post: @forum_post %>

<%= link_to 'Mostrar Publicación', [@forum_post.forum_thread, @forum_post]%> |
<%= link_to 'Volver Atrás', forum_thread_forum_posts_path(@forum_post.forum_thread) %>

app/views/forum_posts/index.html.erb
<h1><%= @forum_thread.subject %></h1>

<% if user_signed_in? %>
  <% rep = 0 %>
  <% @forum_thread.forum_posts.where(user_id: current_user.id).each do |post| %>
    <% rep += post.get_likes.size %>
    <% rep -= post.get_dislikes.size %>
  <% end %>
  <p>Reputación en este foro: <%= rep %></p>
  <% if rep > 0 and not ya_postulo(current_user.id, @forum_thread.id) %>
    <p><strong>
      Tu reputacion es muy alta, ¿quieres ser moderador? <%= button_to 'Postular', {controller: "requests", action: :create, user_id: current_user.id, forum_thread_id: @forum_thread.id}, method: :post %>
    </strong></p>
  <% elsif ya_postulo(current_user.id, @forum_thread.id) %>
    <% request = Request.all.where(user_id: current_user.id, forum_thread_id: @forum_thread.id).last %>
    <% if request.state == "Pendiente" %>
      <strong><p>Ya has postulado a moderador!! Estado: <%= request.state %></p></strong>
    <% elsif request.state == "Aceptado" %>
      <strong><p>Felicitaciones, eres moderador !</p></strong>
      <% modera = true %>
    <% elsif request.state == "Rechazado" %>
      <strong><p>Tu solicitud para ser moderador ha sido rechazada, puedes volver a intentarlo!</p></strong>
      <% request.destroy %>
    <% end %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <% if current_user.follows?(@forum_thread) or current_user.id == @forum_thread.user_id %>
    <%= link_to 'Nueva publicación', new_forum_thread_forum_post_path(@forum_thread) %> | 
    <%= link_to 'Nueva encuesta', new_forum_thread_poll_path(@forum_thread) %> | 
  <% else %>
    <div style="border: 1px solid black; background-color: lightgray;">
      <p>
        Para poder publicar debes seguir el foro!
        <%= link_to 'Seguir', follows_path(@forum_thread) %>
      </p>
    </div>
  <%end%>
<% else %>
  <div style="border: 1px solid black; background-color: lightgray;">
    <p>
      Inicia sesion o registrate para participar!
    </p>
  </div>
<%end%>
<%= link_to 'Volver Atrás', forum_threads_path %>
<br>
<br>

<%= search_form_for @q, url: forum_thread_forum_posts_path(@forum_thread), html: { class: "form-inline" } do |f| %>
  <%= f.search_field :title_or_body_cont, placeholder: "Buscar publicacion...", class: "form-control" %>
<%end%>



<p> Hay <%= @forum_posts.count %> publicaciones y <% @forum_thread.polls.count %> encuestas.</p>
<% @forum_posts.each do |forum_post| %>
  <div style="border-bottom: 1px solid black; background-color:#0000;">
    <h3><%= forum_post.title %></h3>
    <small>Creado por <strong><%= forum_post.user.username %></strong>. <%= forum_post.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>. <strong><%= forum_post.get_likes.size %> Me Gusta.  </strong><strong><%= forum_post.get_dislikes.size %> No me Gusta.  </strong>
    </small>

    <br>
    <p>
      <%= forum_post.body.html_safe %>
    </p>
    <% if can? :update, forum_post %>
      <%= link_to 'Editar', [:edit, @forum_thread, forum_post] %> |
    <% end %>
    <% if (can? :destroy, forum_post) or modera %>
      <%= link_to 'Eliminar', forum_thread_forum_post_path(forum_post.forum_thread, forum_post), method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar la publicación?' } %>
    <% end %>
    <% if forum_post.comments.any? %>
      <p>
        Hay <%= forum_post.comments.count%> comentario(s) |
        <%= link_to 'Ver Publicación', forum_thread_forum_post_path(forum_post.forum_thread, forum_post) %>
      </p>
    <% else %>
      <p>
        No hay comentarios |
        <%= link_to 'Ver Publicación', forum_thread_forum_post_path(forum_post.forum_thread, forum_post) %>
      </p>
    <% end %>

    <p>
      <%if user_signed_in? %>
        <% if not current_user.voted_for? forum_post and current_user.id != forum_post.user_id %>
          <%= link_to "Me gusta", forum_thread_forum_post_likes_path(forum_post.forum_thread, forum_post) %> |
        
          <%= link_to "No me gusta", forum_thread_forum_post_dislikes_path(forum_post.forum_thread, forum_post) %> |
        <%end%>
        <% if not current_user.follows?(forum_post) %>
            <%= link_to "Anadir a favoritos", forum_thread_forum_post_favoritos_path(forum_post.forum_thread, forum_post) %>
        <% end %>
      <%end%>
    </p>
  <% end %>
  </div>
<% @forum_thread.polls.each do |poll| %>
  <div style="border-bottom: 1px solid black; background-color:#0000;">
  <h3><%= poll.question %></h3>
  <% poll.answers.each do |a| %>
    <p><%= a.content %> | <%= link_to 'Votar', '#' %></p>
  <% end %>


  <p>Current results:</p>


<% end %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/forum_posts/new.html.erb
<h1>Nueva Publicación</h1>

<%= render 'form', forum_post: @forum_post %>

<%= link_to 'Volver Atrás', forum_threads_path(@forum_post.forum_thread) %>

app/views/forum_posts/show.html.erb
<% if ya_postulo(current_user.id, @forum_thread.id) %>
  <% request = Request.all.where(user_id: current_user.id, forum_thread_id: @forum_thread.id).last %>
  <% if request.state == "Aceptado" %>
    <strong><p>Felicitaciones, eres moderador !</p></strong>
    <% modera = true %>
  <% end %>
<% end %>
<div style="border-bottom: 1px solid black; background-color:#0000;">

  <h3><%= @forum_post.title %></h3>
  <small>Creado por <strong><%= @forum_post.user.username %>. </strong>
  <%= @forum_post.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>. 
  <% if @forum_post.created_at != @forum_post.updated_at %>
    <strong>(Update <%= time_ago_in_words(@forum_post.updated_at) %> ago)</strong>
  <% end %>
  </small>

    <br>
    <p>
      <%= @forum_post.body.html_safe %>
    </p>
      <% if can? :update, @forum_post %>
        <%= link_to 'Editar', [:edit, @forum_thread, @forum_post] %>
      <% end %>
      <% if (can? :destroy, @forum_post) or modera %>
        <%= link_to 'Eliminar', forum_thread_forum_post_path(@forum_post.forum_thread, @forum_post), method: :delete, data: { confirm: '¿Estás seguro?' } %>
      <% end %>
  
  <% if @forum_post.comments.any? %>
    <h4>Comentarios</h4>
    <%= render @forum_post.comments %>
  <% end %>

  <hr>

  <% if user_signed_in? %>
    <% if current_user.follows?(@forum_thread) or current_user.id == @forum_thread.user_id %> 
      <p>Añadir Comentario</p>
      <%= form_for([@forum_thread, @forum_post, @forum_post.comments.build]) do |f| %>
        <%= f.text_area :content %>
        <%= f.hidden_field :@forum_post, value: 5 %>
        <br>
        <br>
        <a class="waves-effect waves-light btn light-blue darken-2">
        <%= f.submit %>
        </a>
        <br>
      <% end %>

    <% else %>
    <div style="border: 1px solid black; background-color: lightgray;">
      <p>
        Para poder comentar y poner likes debes seguir el foro!
      </p>
    </div>

    <% end %>

  <% else %>
    <div style="border: 1px solid black; background-color: lightgray;">
      <p>
        Inicia sesion o registrate para participar!
      </p>
    </div>

  <% end %>
</div>

<%= link_to 'Volver Atrás', forum_thread_forum_posts_path %>
<% if user_signed_in? and current_user.follows?(@forum_post) %>
  <div>
  <%= link_to 'Volver a Mis publicaciones favoritas', mis_publicaciones_path(current_user) %>
  </div>
<%end%>

<div>
<%= link_to 'Volver a las publicaciones del foro', forum_thread_forum_posts_path %>
</div>