config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  get 'forum_thread/:id/follows', to: 'forum_threads#follows', as: :follows
  get 'forum_thread/:id/unfollows', to: 'forum_threads#unfollows', as: :unfollows
  get 'user/:id/mis_foros', to: 'users#mis_foros', as: :mis_foros
  get 'forum_thread/:id/forum_posts?forum_thread=:id/likes', to: 'forum_posts#likes', as: :likes
  get 'user/:id/mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
  get 'estadisticas', to: 'estadisticas#show', as: :estadisticas
  #match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users do
    get 'mis_publicaciones', to: 'users#mis_publicaciones', as: :mis_publicaciones
    get 'destroy', to: 'users#destroy', as: :destroy
  end

  resources :forum_threads do
    resources :requests do

      get 'aceptar', to: 'requests#aceptar', as: :aceptar
      get 'rechazar', to: 'requests#rechazar', as: :rechazar
    end

    resources :polls do
      resources :answers do
        put 'vote', to: 'answers#vote', as: :vote
      end
    end

  	resources :forum_posts do

      get 'likes', to: 'forum_posts#likes', as: :likes
      get 'favoritos', to: 'forum_posts#favoritos', as: :favoritos
      get 'sacar_favoritos', to: 'forum_posts#sacar_favoritos', as: :sacar_favoritos
      get 'dislikes', to: 'forum_posts#dislikes', as: :dislikes

      resources :comments do
        get 'likes', to: 'comments#likes', as: :likes
        get 'dislikes', to: 'comments#dislikes', as: :dislikes
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum_thread.rb
# frozen_string_literal: true

class ForumThread < ApplicationRecord
  belongs_to :user
  has_many :forum_posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :polls, dependent: :destroy

  validates :subject, presence: true

  acts_as_followable
end

app/controllers/forum_threads_controller.rb
# frozen_string_literal: true

class ForumThreadsController < ApplicationController
  before_action :set_forum_thread, only: %i[show edit update destroy]

  # GET /forum_threads
  # GET /forum_threads.json
  def index
    @q = ForumThread.search(params[:q])
    @forum_threads = @q.result
  end

  # GET /forum_threads/1
  # GET /forum_threads/1.json

  def follows
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_thread = ForumThread.find(params[:id])
    @user.follow!(@forum_thread)
    redirect_to forum_threads_path
  end

  def unfollows
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @forum_thread = ForumThread.find(params[:id])
    @user.unfollow!(@forum_thread)
    redirect_to mis_foros_path(@user)
  end

  def show
    redirect_to forum_thread_forum_posts_path(@forum_thread.id,
                                              forum_thread: @forum_thread)
  end

  # GET /forum_threads/new
  def new
    @forum_thread = ForumThread.new
  end

  # GET /forum_threads/1/edit
  def edit; end

  # POST /forum_threads
  # POST /forum_threads.json
  def create
    @forum_thread = ForumThread.new(forum_thread_params)
    @forum_thread.user = current_user

    respond_to do |format|
      if @forum_thread.save
        current_user.follow!(@forum_thread)
        format.html do
          redirect_to @forum_thread,
                      notice: 'Forum thread was successfully created.'
        end
        format.json { render :show, status: :created, location: @forum_thread }
      else
        format.html { render :new }
        format.json do
          render json: @forum_thread.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /forum_threads/1
  # PATCH/PUT /forum_threads/1.json
  def update
    respond_to do |format|
      if @forum_thread.update(forum_thread_params)
        format.html do
          redirect_to @forum_thread,
                      notice: 'Forum thread was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @forum_thread }
      else
        format.html { render :edit }
        format.json do
          render json: @forum_thread.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /forum_threads/1
  # DELETE /forum_threads/1.json
  def destroy
    @forum_thread.destroy
    respond_to do |format|
      format.html do
        redirect_to forum_threads_url,
                    notice: 'Forum thread was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end

  def forum_thread_params
    params.require(:forum_thread).permit(:user_id, :subject, :forum_thread_id)
  end
end

app/helpers/forum_threads_helper.rb
# frozen_string_literal: true

module ForumThreadsHelper
  def calcular_popularidad(forum_thread)
    rep = 0
    forum_thread.forum_posts.each do |forum_post|
      rep += forum_post.get_likes.size
      rep -= forum_post.get_dislikes.size
      forum_post.comments.each do |comment|
        rep += comment.get_likes.size
        rep -= comment.get_dislikes.size
      end
    end
    rep
  end

  def mas_populares
    valores = []
    populares = {}
    ForumThread.all.each do |forum_thread|
      valores += [calcular_popularidad(forum_thread)]
    end
    valores.sort! { |x, y| y <=> x }
    valores = valores[0, 5]
    valores.each do |valor|
      ForumThread.all.each do |forum_thread|
        if  valor.eql? calcular_popularidad(forum_thread)
          populares[forum_thread] = calcular_popularidad(forum_thread)
        end
      end
    end
    populares
  end
end

app/views/forum_threads/_form.html.erb
<%= form_with(model: forum_thread, local: true) do |form| %>
  <% if forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Contenido, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= form.text_area :subject, id: :forum_thread_subject, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <br>
        <%= form.submit "Crear Foro", class:"valign-wrapper",class:"waves-effect waves-light btn light-blue darken-2"%>
    </div>
  </div>

  <% end %>

app/views/forum_threads/edit.html.erb
<h3>Editar Foro</h3>

<%= render 'form', forum_thread: @forum_thread %>

<%= link_to 'Mostrar', @forum_thread %> |
<%= link_to 'Volver Atrás', forum_threads_path %>

app/views/forum_threads/index.html.erb
<h1>Foros</h1>
<p class="navbar-text pull-left">
  <% if user_signed_in? %>
    <h3>Notificaciones</h3><small>Última conexión: (<%= current_user.last_sign_in_at.strftime('%a, %d %b %Y %H:%M:%S') %>)</small>
    <div class="notifications">
      <ul>
        <% if current_user.followees(ForumThread).any? %>
          <% current_user.followees(ForumThread).each do |forum| %>
            <% forum.forum_posts.each do |post| %>
              <% if post.created_at > current_user.last_sign_in_at %>
                <li>Nueva Publicación en <%= forum.subject %>, <%= link_to 'Ver', forum_thread_forum_post_path(forum, post)%></li>
              <% elsif post.updated_at > current_user.last_sign_in_at %>
                <li>Publicación actualizada en <%= link_to forum.subject, forum_thread_path(forum) %>, <%= link_to 'Ver', forum_thread_forum_post_path(forum, post)%></li>
              <% end %>
              <% post.comments.each do |comment| %>
                <% if comment.created_at > current_user.last_sign_in_at %>
                  <li>Nuevo comentario en <%= link_to post.title, forum_thread_forum_post_path(forum, post)%></li>
                <% elsif comment.updated_at > current_user.last_sign_in_at %>
                  <li>Comentario actualizado en <%= link_to post.title, forum_thread_forum_post_path(forum, post)%></li>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <%= link_to 'Crear Nuevo Foro', new_forum_thread_path %>
  <% else %>
    Para crear un foro debe iniciar sesión.
  <% end %>
</p>

<div class="row">
  <div class="column">
    <h2>Recientes</h2><p><small>Los últimos 5 creados...</small></p>
      <% if ForumThread.any? %>
        <ul>
          <% ForumThread.order("created_at DESC").limit(5).each do |forum_thread| %>
            <p>
              <div>
                <strong><%= link_to forum_thread.subject, forum_thread %></strong>
              </div>
              <div>
                <small>
                  Created by <strong><%= forum_thread.user.username %></strong> at <%= forum_thread.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>
                </small>
                &emsp;<strong>Publicaciones: <%= forum_thread.forum_posts.count %></strong>
              </div>
              <div>
                <% if user_signed_in? %>
                  <% if not current_user.follows?(forum_thread) %>
                    <%= link_to 'Seguir', follows_path(forum_thread) %>
                  <% end %>
                <% end %>
              </div>
            </p>
          <% end %>
        </ul>
      <% else %>
        <p>No hay resultados...</p>
      <% end %>
  </div>

  <div class="column">
    <h2>Todos</h2>
    <strong>Búsqueda</strong>
    <%= search_form_for @q, html: { class: "form-inline" } do |f| %>
      <%= f.search_field :subject_cont, placeholder: "Buscar foro...", class: "form-control" %>
    <%end%>
    <% if @forum_threads.any? %>
      <ul>
        <% @forum_threads.each do |forum_thread| %>
          <div class="row">
            <p>
              <div>
                <strong><%= link_to forum_thread.subject, forum_thread %></strong>
              </div>

              <div>
                <% if can? :destroy, forum_thread %>
                  <td><%= link_to 'Eliminar', forum_thread, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
                <% end %>
              </div>

              <div>
                <small>
                  Created by <strong><%= forum_thread.user.username %></strong> at <%= forum_thread.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>
                </small>
                &emsp;<strong>Publicaciones: <%= forum_thread.forum_posts.count %></strong>
              </div> 

              <div>
                <% if user_signed_in? %>
                  <% if not current_user.follows?(forum_thread) %>
                    <%= link_to 'Seguir', follows_path(forum_thread) %>
                  <% end %>
                <%end%>
              </div>

            </p>
          </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No hay resultados...</p>
    <% end %>
  </div>

  <div class="column">
    <h2>Populares</h2>
    <% if ForumThread.any? %>
      <% mas_populares.keys.each do |popular| %>
        <p><strong><%= link_to popular.subject, popular %></strong></p>
        <div>
          <small>
            Created by <strong><%= popular.user.username %></strong> at <%= popular.created_at.strftime('%a, %d %b %Y %H:%M:%S') %>
          </small>
          <small><strong>Popularidad: <%= mas_populares[popular] %></strong></small>
          &emsp;<strong>Publicaciones: <%= popular.forum_posts.count %></strong>
        </div>
      <% end %>
    <% else %>
      <p>No hay resultados...</p>
    <% end %>
  </div>
</div>

<style>
  * {
    box-sizing: border-box;
  }

  body {
    margin: 0;
  }

  .column {
    float: left;
    width: 33.33%;
    padding: 15px;
  }

  .row:after {
    content: "";
    display: table;
    clear: both;
  }

</style>

app/views/forum_threads/new.html.erb
<h3>Nuevo Foro</h3>


<%= render 'form', forum_thread: @forum_thread %>
<div class="col-sm-6 col-sm-offset-2">
	<%= link_to 'Volver Atrás', forum_threads_path %>
</div>

app/views/forum_threads/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @forum_thread.subject %></h1>

<%= link_to 'Ver Publicaciones', forum_thread_forum_posts_path(@forum_thread) %> |

<%= link_to 'Volver Atrás', forum_threads_path %>